basePath: /api
definitions:
  handlers.LoginRequest:
    properties:
      password:
        example: password123
        type: string
      username:
        example: johndoe
        type: string
    type: object
  handlers.PurchaseItemReq:
    properties:
      item_id:
        example: 1
        type: integer
      qty:
        example: 10
        type: integer
    type: object
  handlers.PurchaseReq:
    properties:
      items:
        items:
          $ref: '#/definitions/handlers.PurchaseItemReq'
        type: array
      supplier_id:
        example: 1
        type: integer
    type: object
  handlers.RegisterRequest:
    properties:
      password:
        example: password123
        type: string
      role:
        example: admin
        type: string
      username:
        example: johndoe
        type: string
    type: object
  models.Item:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
  models.Purchasing:
    properties:
      createdAt:
        type: string
      date:
        type: string
      details:
        items:
          $ref: '#/definitions/models.PurchasingDetail'
        type: array
      grandTotal:
        type: number
      id:
        type: integer
      supplier:
        $ref: '#/definitions/models.Supplier'
      supplierID:
        type: integer
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.PurchasingDetail:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      item:
        $ref: '#/definitions/models.Item'
      itemID:
        type: integer
      purchasingID:
        type: integer
      qty:
        type: integer
      subTotal:
        type: number
    type: object
  models.Supplier:
    properties:
      address:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API untuk manajemen purchasing, items, suppliers, dan pembelian
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Purchasing Management API
  version: "1.0"
paths:
  /items:
    get:
      consumes:
      - application/json
      description: Get list of all items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Item'
            type: array
      security:
      - Bearer: []
      summary: Get all items
      tags:
      - Items
    post:
      consumes:
      - application/json
      description: Create a new item with name, stock and price
      parameters:
      - description: Item Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create new item
      tags:
      - Items
  /items/{id}:
    delete:
      consumes:
      - application/json
      description: Delete item by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Delete item
      tags:
      - Items
    get:
      consumes:
      - application/json
      description: Get single item by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get item by ID
      tags:
      - Items
    put:
      consumes:
      - application/json
      description: Update item by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Item Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Update item
      tags:
      - Items
  /login:
    post:
      consumes:
      - application/json
      description: Login with username and password to get JWT token
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Auth
  /purchasings:
    get:
      consumes:
      - application/json
      description: Get list of all purchases with supplier and user details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Purchasing'
            type: array
      security:
      - Bearer: []
      summary: Get all purchases
      tags:
      - Purchasings
    post:
      consumes:
      - application/json
      description: Create a new purchase order. Will automatically update item stock.
      parameters:
      - description: Purchase Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.PurchaseReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create new purchase
      tags:
      - Purchasings
  /purchasings/{id}:
    delete:
      consumes:
      - application/json
      description: Delete purchase by ID. Will restore item stock automatically.
      parameters:
      - description: Purchase ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Delete purchase
      tags:
      - Purchasings
    get:
      consumes:
      - application/json
      description: Get single purchase by ID with full details
      parameters:
      - description: Purchase ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Purchasing'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get purchase by ID
      tags:
      - Purchasings
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with username, password and role
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register new user
      tags:
      - Auth
  /suppliers:
    get:
      consumes:
      - application/json
      description: Get list of all suppliers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Supplier'
            type: array
      security:
      - Bearer: []
      summary: Get all suppliers
      tags:
      - Suppliers
    post:
      consumes:
      - application/json
      description: Create a new supplier with name, email and address
      parameters:
      - description: Supplier Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Supplier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Supplier'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create new supplier
      tags:
      - Suppliers
  /suppliers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete supplier by ID
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Delete supplier
      tags:
      - Suppliers
    get:
      consumes:
      - application/json
      description: Get single supplier by ID
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Supplier'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get supplier by ID
      tags:
      - Suppliers
    put:
      consumes:
      - application/json
      description: Update supplier by ID
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      - description: Supplier Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Supplier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Supplier'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Update supplier
      tags:
      - Suppliers
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
